### ISSUE TITLE
aessbos.pdf, page 4, error in equations (6) and (7)

### ISSUE THREAD

**Issue by jeffareid** [bpdegnan/aes#1]
There should be no x terms in the second lines of equations (6) and (7). The start of the second line in equation (6) should be changed from (n0 x + n1 A) to (n0 + n1 A). The start of the second line in equation (7) should be changed from (n0 x + n1) to (n0 + n1).

**Comment by bpdegnan** [comment]
Thank you for pointing this out.  Let me check this out and I'll get back
to you once I update it.
Sadly, the github documentation is not as complete as my internal documents
and I might have updated it.

Cheers,
Brian Degnan, Ph.D.

**Comment by jeffareid** [comment]
I caught this issue while modifying some code I had from around 1990 used with a primitive polynomial as opposed to AES's irreducible but not primitive polynomial. I had a corresponding doc file last updated in 2007, converted to pdf in 2018 (link below). In this case, a brute force approach is not needed to look for compatible fields. When doing sub-field mapping with a primitive polynomial, such as GF(2^8) based on x^8 + x^4 + x^3 + x^2 + 1, then after choosing a basis for GF(16^2), there are 4 of 64 possible polynomial of the form x^2 + Ax + B, which will be the 4 roots of x^8 + x^4 + x^3 + x^2 + 1 treated as if it had 4 bit coefficients with values 0 and 1. Link to the pdf version of this (it doesn't mention that the 4 polys are roots of the GF(2^8) poly).

http://rcgldr.net/misc/m8to44.pdf

**Comment by jeffareid** [comment]
Later if you have the time, you might want to add an explanation for how the mapping matrix was created (powers of 0x1f for GF(2^8), powers of 0x10 for GF(16^2)).

**Comment by jeffareid** [comment]
Later, if you have the time, you might consider adding an explanation for the parameters chosen to map GF(2^8) to GF((2^2)^2)^2), and how the mapping data is generated. For example, there are 128 possible polynomials to use as the "primitive" for GF(2^8). Based on the mapping data in your document, I was able to reverse engineer it and determine that the primitive is x^4+x^3+x^2+x+1 (0x1f), but I didn't see this mentioned anywhere in the document.

**Comment by bpdegnan** [comment]
I finally got a moment to look into this.   There was indeed a typo, which I have addressed and committed.  The design is based off of Satoh et al. (ref 6).   Thank you for reading my document.

**Comment by jeffareid** [comment]
This is a follow up about the matrices, not the issue. I created a brief document about the matrices used to map between GF(2^8) and GF(((2^2)^2^2). None of the articles I've found on this mapping include how the matrices are constructed. Your's is the most complete since it includes tables for powers of both fields primitive elements.  Is this something that most readers are expected to recognize by just looking at the matrices themselves?

https://github.com/jeffareid/finite-field/blob/master/Composite%20Field%20Mapping%20Example.pdf

**Comment by bpdegnan** [comment]
Firstly, I appreciate that you actually read my document.  I generally
write documentation for just me, and it's nice to have someone look over my
shoulder and check my work.
Those matrices are my notes as I tend to work from paper and transcribe
it.  I need to pull my notebook from the shelf and try to expand upon it
this weekend.  I do not recall the source of the construction, but it was
likely me just pushing through it. It's also could be from the Satoh et al.
(which is in Japanese) that is referenced in the paper.   I will get back
to you in a few days.

**Comment by jeffareid** [comment]
Thanks. I've seen a few conversions of that Satoh paper, none of them explain the math behind the construction of those matrices. It's possible that the Satoh paper doesn't either. You paper seems the most complete, as it includes tables VII and VIII, which at least have the mapping explained as a table lookup, for example in table VII map[02] = 5f, and in table VIII, inverse_map[5f] = 02. I've seen similar papers that involve different parameters and those don't explain the construction either. 

What got me started on this, was a question specifically asking how the matrices are constructed, part of which is searching for any element of GF(2^8) that stratifies the constraints that map(a+b) = map(a)+map(b), and map(ab) = map(a)map(b). Worse yet, the inversion matrix in the question has 2 errors. I used your document as a reference for that student, and explained the construction.

https://stackoverflow.com/questions/59386141

I"m planning to include the construction process as part of a Wikipedia article, which why I created that example mapping paper showing how the matrices are constructed. If you are able to update your paper, I will cite that as a reference.

Thanks again for your work on this.

**Comment by bpdegnan** [comment]
just wanted to mention that I still have this in my list.  It's slowly
moving up.

**Comment by bpdegnan** [comment]
I decided that I should just get this out of the way.    The construction
for the inversion for the AES polynomial I apparently found here:
https://www.researchgate.net/publication/2621085_Efficient_Implementation_of_the_Rijndael_S-box
(mine is from a book)
That, combined with a background in abstract algebra, allowed me to just
push through the whole thing on paper.

Feel free to contact me directly and I can walk you through any steps that
you'd like.

**Comment by jeffareid** [comment]
> The construction for the inversion for the AES polynomial I apparently found here:

 

I meant the construction of the 8 row by 8 bit matrices used to map between GF(2^8) and GF(16^2). For example, I created a pdf file showing an example of the  mapping of AES GF(2^8) to GF(((2^2)^2)^2) used in your document:

 

https://github.com/jeffareid/finite-field/blob/master/Composite%20Field%20Mapping%20Example.pdf

 

https://github.com/bpdegnan/aes/blob/master/aes-sbox/documentation/aessbox.pdf

 

In your document, the mapping matrix is shown and the mapping tables are shown, which is more information than I’ve seen in most of the online documents. The mapping matrix maps GF(2^8) values {0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01} to GF(16^2) values {0xfc, 0x4b, 0xb0, 0x46, 0x74, 0x7c, 0x5f, 0x01}. However, unless I just missed it, your document doesn’t mention that α(x) of GF(2^8) = x^4 + x^3 + x^2 + x + 1, or explain how the mapping matrix works. I explain this mapping in my example pdf file. Another way to state this is to let the array p{…} = GF(2^8) log α(x) {0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01}, then the matrix column values are GF(16^2) β(x)^p{…}.

 

Jeff
